alias tfinit='terraform init'
alias tfpln='terraform plan'
alias tfapy='terraform applay'
alias tfdl='terraform destroy'
alias tffmt='terraform fmt -recursive'
alias tfshow='terraform show'

alias tfsl='terraform state list'
alias tfsrm='terraform state rm $1'
alias tfimp='terraform import $1'
